-   id: prepend-jira-link
    name: Jira Ticket Link Prepender
    description: Appends ticket number and link below commit message
    entry: prepender-jira-link.sh
    language: script
    files: ''
    always_run: true
    stages: [prepare-commit-msg]
